# Generated by Django 4.2.7 on 2023-11-29 15:37

import Python_Web_Framework.main_app.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('town', models.CharField(max_length=20, validators=[Python_Web_Framework.main_app.validators.validate_char_field])),
                ('address', models.CharField(max_length=100)),
                ('building_number', models.PositiveIntegerField(blank=True, null=True)),
                ('entrance', models.CharField(max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('family_name', models.CharField(max_length=30, validators=[Python_Web_Framework.main_app.validators.validate_char_field])),
                ('floor', models.PositiveIntegerField()),
                ('apartment', models.PositiveIntegerField()),
                ('number_of_people', models.PositiveIntegerField()),
                ('is_using_lift', models.BooleanField(default=True)),
                ('is_occupied', models.BooleanField(default=True)),
                ('fixed_fee', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_clients', to='main_app.customer')),
            ],
            options={
                'ordering': ['customer', 'apartment'],
                'unique_together': {('apartment', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=30, validators=[Python_Web_Framework.main_app.validators.validate_char_field])),
                ('last_name', models.CharField(max_length=30, validators=[Python_Web_Framework.main_app.validators.validate_char_field])),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10, validators=[Python_Web_Framework.main_app.validators.validate_phone_number])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerMonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=64)),
                ('year', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=10)),
                ('electricity_common', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity_lift', models.DecimalField(decimal_places=2, max_digits=10)),
                ('internet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_lift', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_cleaner', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_manager_and_cashier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repairs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_monthly_bills', to='main_app.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerClientMonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=64)),
                ('year', models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], max_length=10)),
                ('electricity_common', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electricity_lift', models.DecimalField(decimal_places=2, max_digits=10)),
                ('internet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maintenance_lift', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_cleaner', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_manager_and_cashier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repairs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('others', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_client_monthly_bills', to='main_app.customerclient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='main_app.user'),
        ),
    ]
